name: ci/cd pipeline
on:
  push:
    branches:
      - main
    # paths:
    #   - devops/hello/**
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/hello
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: install dependencies
        id: npmi
        run: |
          npm i
      - name: run test
        id: test
        run: |
          npm test 
          echo "audit=$(npm audit --audit-level=low)" >> $GITHUB_OUTPUT
      - name: check install
      # echo "npmi=$(npm i)\n" >> $GITHUB_OUTPUT
        # if: "!contains(${{steps.npmi.outputs.test}}, 'found 0 vulnerabilities')"
        run: |
          echo ${{steps.test.outputs.*}}
          exit 1
      - name: check output

        if: "${{ ! steps.test == 'passed!' }}"
        run: exit 1