name: ci/cd pipeline
on:
  push:
    branches:
      - main
    # paths:
    #   - devops/hello/**
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/hello
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: install dependencies
        id: npmi
        run: |
          npm i
          echo "audit=$(npm audit --audit-level=low)" >> $GITHUB_OUTPUT
      - name: run test
        id: test
        run: |
          {
            echo 'test<<EOF'
            npm test
            echo EOF
          }>> "$GITHUB_OUTPUT"
      - name: check install
      # echo "npmi=$(npm i)\n" >> $GITHUB_OUTPUT
        if: "!contains(${{steps.npmi.outputs.audit}}, 'found 0 vulnerabilities')"
        run: |
          echo "${{steps.npmi.outputs.audit}}"
          exit 1
      - name: check output
        if: "!contains(${{steps.test.outputs.test}}, 'passed!')"
        run: exit 1