name: ci/cd pipeline
on:
  push:
    branches:
      - main
    # paths:
    #   - devops/hello/**
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/hello
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: install dependencies
        id: i
        run: |
          npm i
      - name: run test
        id: test
        run: |
          echo "npm test=$(npm test)" >> $GITHUB_OUTPUT
      - name: check install
        if: "!contains(${{steps.i.outputs.*}}, 'found 0 vulnerabilities')"
        run: |
          echo ${{steps.i.outputs.*}}
          exit 1
      - name: check output

        if: "${{ ! steps.test == 'passed!' }}"
        run: exit 1