name: (Dev) Terraform Plan & Apply
on:
  push:
    branches:
      - main
    paths:
      - tf/**
  pull_request:
    branches:
      - main
    paths:
      - tf/**
env: 
  environment: dev
  workingDir: "./tf"

jobs:
  job:
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    name: Terraform Plan ${{ env.environment }}

    environment: ${{ env.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.workingDir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: terraform init -upgrade
        id: init
        run: terraform init -backend-config=${{env.tfInitConfigFile}} -upgrade


      - name: terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        if: "${{ github.event_name == 'pull_request' }}"
        run: |
          terraform plan 
        continue-on-error: true
      - name: Terraform Apply 
        if: "${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}"
        run: terraform apply

